In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("season-0910_csv.csv")

In [4]:
df.head(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,E0,2009-08-15,Aston Villa,Wigan,0,2,A,0,1,A,...,2.04,1.92,1.91,1.81,21,0.0,1.28,1.22,4.40,3.99
1,E0,2009-08-15,Blackburn,Man City,0,2,A,0,1,A,...,2.15,2.04,1.78,1.71,24,0.0,2.58,2.38,1.60,1.54
2,E0,2009-08-15,Bolton,Sunderland,0,1,A,0,1,A,...,2.25,2.12,1.70,1.66,23,0.0,1.68,1.61,2.33,2.23
3,E0,2009-08-15,Chelsea,Hull,2,1,H,1,1,D,...,1.67,1.58,2.44,2.26,22,0.0,1.03,1.02,17.05,12.96
4,E0,2009-08-15,Everton,Arsenal,1,6,A,0,3,A,...,2.20,2.06,1.77,1.70,24,0.0,2.27,2.20,1.73,1.63
5,E0,2009-08-15,Portsmouth,Fulham,0,1,A,0,1,A,...,2.28,2.12,1.70,1.65,23,0.0,1.98,1.83,2.05,1.95
6,E0,2009-08-15,Stoke,Burnley,2,0,H,2,0,H,...,2.25,2.10,1.71,1.67,22,0.0,1.45,1.39,3.05,2.85
7,E0,2009-08-15,Wolves,West Ham,0,2,A,0,1,A,...,2.16,2.03,1.80,1.72,22,0.0,1.95,1.85,2.00,1.92
8,E0,2009-08-16,Man United,Birmingham,1,0,H,1,0,H,...,1.69,1.62,2.35,2.18,20,0.0,1.04,1.02,15.00,11.42
9,E0,2009-08-16,Tottenham,Liverpool,2,1,H,1,0,H,...,2.07,1.95,1.85,1.79,21,0.0,2.38,2.24,1.73,1.61